### ISSUE TITLE
apollo_encoder::Value::String serialization never uses escape sequences

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/apollo-rs#612]
## Description

Serialization with apollo-encoder is incorrect for some string values.

A better way to test this would be checking that re-parsing the serialization gives the same string value, but this runs into https://github.com/apollographql/apollo-rs/issues/609 and https://github.com/apollographql/apollo-rs/issues/611.

### Steps to reproduce

`crates/apollo-encoder/src/value.rs`
```rust
#[cfg(test)]
mod tests {
    use super::Value;

    #[test]
    fn escape_controls() {
        // NULL is not a SourceCharacter: it can only be represented by a unicode escape
        // in a non-block string.
        assert_eq!(
            Value::String("  \0  ".into()).to_string(),
            "\"  \\u0000  \""
        );
    }

    #[test]
    fn escape_triple_double_quote() {
        let serialized = Value::String("  \"\"\"  ".into()).to_string();
        // Either block string or non-block string works, with corresponding escape sequences
        assert!(
            serialized == "\"  \\\"\\\"\\\"  \"" || serialized == "\"\"\"  \\\"\"\"  \"\"\"",
            "got {serialized:?}"
        );
    }

    #[test]
    fn leading_trailing_double_quote() {
        let serialized = Value::String("\"  \"".into()).to_string();
        // In a block string, the only way to make this not ambigous with the end marker
        // would be to rely on leading/trailing empty lines being stripped by the parser
        assert!(
            serialized == "\"\\\"  \\\"\"" || serialized == "\"\"\"\n\"  \"\n\"\"\"",
            "got {serialized:?}"
        );
    }
}
```

### Expected result

Tests pass

### Actual result

```rust
---- value::tests::escape_controls stdout ----
thread 'value::tests::escape_controls' panicked at 'assertion failed: `(left == right)`
  left: `"\"  \0  \""`,
 right: `"\"  \\u0000  \""`', crates/apollo-encoder/src/value.rs:125:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- value::tests::leading_trailing_double_quote stdout ----
thread 'value::tests::leading_trailing_double_quote' panicked at 'got "\"\"\"\"  \"\"\"\""', crates/apollo-encoder/src/value.rs:146:9

---- value::tests::escape_triple_double_quote stdout ----
thread 'value::tests::escape_triple_double_quote' panicked at 'got "\"\"\"  \"\"\"  \"\"\""', crates/apollo-encoder/src/value.rs:135:9
```

### Environment

- `apollo-rs` crate: apollo-encoder
- Crate version: `main` 126816fc6717bf5df429dac48cd71995e5538a7d

**Comment by goto-bus-stop** [comment]
Fixed in apollo-compiler 1.0
